/**
 * Deployment HANDOFF — BuildMyStack's complementary value vs Coolify/Dokploy.
 *
 * BuildMyStack is the guided *composer*; it does not compete with a deploy
 * panel. The primary "deploy" path is therefore a HANDOFF: hand the user a
 * correct, portable `docker-compose.yml` plus clear, per-target instructions
 * so they can run the stack anywhere (Portainer / Coolify / Dokploy / plain
 * `docker compose`).
 *
 * ── Artifact approach: INLINE compose, `.env` for reference ─────────────────
 * The compose generator (`generateComposeWithSecrets`) inlines every value —
 * including auto-generated passwords — directly into the YAML `environment`
 * blocks. We keep that as the single source of truth: the downloaded
 * `docker-compose.yml` is fully self-contained and runs on its own with no
 * `.env` required.
 *
 * We ALSO emit a `.env` file, but purely for REFERENCE — a record of the
 * generated passwords in `KEY=value` form the user can store safely. The
 * compose does NOT reference `${VAR}` placeholders, so the two artifacts can
 * never drift out of sync: the compose already carries the values, and the
 * `.env` just mirrors them. This is the simplest approach that guarantees the
 * downloaded artifacts work together.
 */

import { generateComposeWithSecrets, type PersistedStack } from '@/lib/stack-persistence';
import { buildStackDocs } from '@/lib/deploy/stack-docs';

/** A single ordered instruction within a deploy-target guide. */
export interface DeployStep {
  title: string;
  detail?: string;
}

/** Which artifact(s) the user pastes/uploads for a given target. */
export type DeployArtifact = 'compose' | 'compose+env';

/** Structured, ordered instructions for one handoff target. */
export interface DeployTargetInstructions {
  id: 'portainer' | 'coolify' | 'dokploy' | 'docker-compose';
  title: string;
  /** One-line description of the target. */
  summary: string;
  steps: DeployStep[];
  /** What the user needs on hand for this target. */
  artifact: DeployArtifact;
}

/** The three deliverables produced from a finished stack. */
export interface ComposeBundle {
  /** Self-contained docker-compose.yml (secret values inlined). */
  composeYaml: string;
  /** A `.env` mirroring the generated secrets, for reference. */
  envFile: string;
  /** Generated secrets keyed as `${slug}.${ENV_VAR}` → value. */
  secrets: Record<string, string>;
}

/**
 * Normalize a `slug.ENV_VAR` secret key into a valid, collision-safe `.env`
 * variable name: non-word characters become `_`, and the whole thing is
 * uppercased (e.g. `postgresql.POSTGRES_PASSWORD` → `POSTGRESQL_POSTGRES_PASSWORD`).
 * Matches the transform used by the live preview's "generated passwords" box.
 */
export function normalizeEnvKey(secretKey: string): string {
  return secretKey.replace(/[^A-Za-z0-9_]+/g, '_').replace(/^_+|_+$/g, '').toUpperCase();
}

/**
 * Build a `.env` file body from generated secrets. Keys are normalized and
 * uppercased; the values are the generated passwords. Includes a short header
 * clarifying that the values are already inlined in the compose.
 */
export function buildEnvFile(secrets: Record<string, string>): string {
  const lines = [
    '# Generated by BuildMyStack — auto-generated passwords for your stack.',
    '# These values are ALSO inlined in docker-compose.yml, so the compose runs',
    '# on its own. Keep this file safe as a record of the generated secrets.',
  ];
  for (const [key, value] of Object.entries(secrets)) {
    lines.push(`${normalizeEnvKey(key)}=${value}`);
  }
  // Trailing newline so the file is a well-formed POSIX text file.
  return `${lines.join('\n')}\n`;
}

/**
 * Prepare the three deliverables from a finished stack: the self-contained
 * compose YAML, a reference `.env`, and the raw generated secrets map.
 */
export function buildComposeBundle(stack: PersistedStack): ComposeBundle {
  const { yaml, secrets } = generateComposeWithSecrets(stack);
  return {
    composeYaml: yaml,
    envFile: buildEnvFile(secrets),
    secrets,
  };
}

/**
 * Per-target handoff instructions. Static content — the artifacts themselves
 * carry the stack-specific values, so the steps only need to explain where to
 * paste/upload them.
 */
export function getDeployTargets(): DeployTargetInstructions[] {
  return [
    {
      id: 'docker-compose',
      title: 'Plain docker compose',
      summary: 'Run it directly on any host with Docker installed.',
      artifact: 'compose+env',
      steps: [
        { title: 'Download docker-compose.yml and .env into an empty folder.' },
        { title: 'Open a terminal in that folder.' },
        {
          title: 'Start the stack.',
          detail: 'docker compose up -d',
        },
        {
          title: 'Check it came up.',
          detail: 'docker compose ps  •  docker compose logs -f',
        },
      ],
    },
    {
      id: 'portainer',
      title: 'Portainer',
      summary: 'Paste the compose into Portainer’s web stack editor.',
      artifact: 'compose',
      steps: [
        { title: 'Open Portainer and go to Stacks → Add stack.' },
        { title: 'Give the stack a name.' },
        {
          title: 'Choose the Web editor and paste the compose below.',
          detail: 'The generated passwords are already inlined, so nothing else is required.',
        },
        { title: 'Click Deploy the stack.' },
      ],
    },
    {
      id: 'coolify',
      title: 'Coolify',
      summary: 'Add it as a Docker Compose resource in Coolify.',
      artifact: 'compose',
      steps: [
        { title: 'In your project, click + New → Resource → Docker Compose.' },
        { title: 'Paste the compose below into the editor.' },
        {
          title: 'Review the environment variables.',
          detail: 'Values are inlined; move any you prefer into Coolify’s Environment Variables tab if you want them managed there.',
        },
        { title: 'Click Deploy.' },
      ],
    },
    {
      id: 'dokploy',
      title: 'Dokploy',
      summary: 'Create a Compose service in Dokploy.',
      artifact: 'compose',
      steps: [
        { title: 'Click Create → Compose.' },
        { title: 'Paste the compose below into the Compose editor.' },
        { title: 'Review the environment variables (already inlined).' },
        { title: 'Click Deploy.' },
      ],
    },
  ];
}

/**
 * Build a README.md a user can drop next to the compose. Thin wrapper over the
 * canonical per-stack docs generator (`buildStackDocs`) — kept for its existing
 * callers/signature so there is a single README, not two competing ones. It
 * produces the full doc (overview, services, ports, volumes, secrets,
 * start/stop, troubleshooting) and optionally appends an environment guide.
 */
export function buildReadme(
  stack: PersistedStack,
  guideMarkdown?: string,
  secrets?: Record<string, string>,
): string {
  return buildStackDocs(stack, { guideMarkdown, secrets });
}
