import { describe, it, expect } from 'vitest';
import { parse as yamlParse } from 'yaml';
import {
  buildComposeBundle,
  buildEnvFile,
  buildReadme,
  getDeployTargets,
  normalizeEnvKey,
} from '../handoff';
import type { PersistedStack } from '@/lib/stack-persistence';
import type { Service } from '@/types/service';
import type { StackService } from '@/types/stack';

const postgresService: Service = {
  id: 1,
  name: 'PostgreSQL',
  slug: 'postgresql',
  description: 'PostgreSQL database',
  dockerImage: 'postgres:18-alpine',
  version: '18',
  category: { id: 1, name: 'Databases', slug: 'databases' },
  ports: [5432],
  environmentVariables: {},
  env: [
    { name: 'POSTGRES_PASSWORD', description: 'Superuser password', required: true, secret: true },
    { name: 'POSTGRES_USER', description: 'Superuser name', required: false, secret: false, default: 'postgres' },
  ],
  volumes: [{ containerPath: '/var/lib/postgresql/data', description: 'Data dir', named: true }],
};

function buildStack(): PersistedStack {
  const services: StackService[] = [
    {
      id: 'ss-pg',
      serviceId: postgresService.id,
      order: 1,
      service: postgresService,
      configuration: {
        environmentVariables: {},
        portMappings: [{ containerPort: 5432, hostPort: 5432 }],
        volumeMounts: [],
        dependsOn: [],
      },
    },
  ];
  return { name: 'db stack', description: '', isPublic: false, services };
}

describe('buildComposeBundle', () => {
  it('returns compose YAML, a reference .env, and the generated secrets', () => {
    const { composeYaml, envFile, secrets } = buildComposeBundle(buildStack());

    // Compose is present and parseable, with the generated password inlined.
    const doc = yamlParse(composeYaml);
    const pgPassword = doc.services.postgresql.environment.POSTGRES_PASSWORD;
    expect(typeof pgPassword).toBe('string');
    expect(pgPassword.length).toBeGreaterThan(16);

    // The secret is returned to the caller under the slug.ENV key.
    expect(secrets['postgresql.POSTGRES_PASSWORD']).toBe(pgPassword);

    // The .env mirrors the same secret value under a normalized key.
    expect(envFile).toContain(`POSTGRESQL_POSTGRES_PASSWORD=${pgPassword}`);
    // .env value equals the value inlined in the compose (artifacts agree).
    expect(envFile).toContain(pgPassword);
  });
});

describe('buildEnvFile', () => {
  it('normalizes keys, uppercases, and keeps a header + trailing newline', () => {
    const env = buildEnvFile({ 'postgresql.POSTGRES_PASSWORD': 'sekret', 'redis.REDIS-PASS': 'pw2' });
    expect(env).toContain('POSTGRESQL_POSTGRES_PASSWORD=sekret');
    expect(env).toContain('REDIS_REDIS_PASS=pw2');
    expect(env.startsWith('#')).toBe(true);
    expect(env.endsWith('\n')).toBe(true);
  });

  it('returns just the header for a stack with no secrets', () => {
    const env = buildEnvFile({});
    expect(env).toContain('# Generated by BuildMyStack');
    expect(env).not.toMatch(/^[A-Z].*=/m);
  });
});

describe('normalizeEnvKey', () => {
  it('uppercases and replaces non-word characters with underscores', () => {
    expect(normalizeEnvKey('postgresql.POSTGRES_PASSWORD')).toBe('POSTGRESQL_POSTGRES_PASSWORD');
    expect(normalizeEnvKey('my-svc.some-key')).toBe('MY_SVC_SOME_KEY');
  });
});

describe('getDeployTargets', () => {
  it('provides ordered instructions for every handoff target', () => {
    const targets = getDeployTargets();
    const ids = targets.map(t => t.id);
    expect(ids).toEqual(expect.arrayContaining(['portainer', 'coolify', 'dokploy', 'docker-compose']));

    for (const target of targets) {
      expect(target.title).toBeTruthy();
      expect(target.steps.length).toBeGreaterThan(0);
      expect(target.steps.every(s => typeof s.title === 'string' && s.title.length > 0)).toBe(true);
      expect(['compose', 'compose+env']).toContain(target.artifact);
    }

    // Plain docker compose is the one that also needs the .env alongside it.
    const plain = targets.find(t => t.id === 'docker-compose');
    expect(plain?.artifact).toBe('compose+env');
    expect(plain?.steps.some(s => `${s.title} ${s.detail ?? ''}`.includes('docker compose up -d'))).toBe(true);

    // Panel targets reference their web editor flow.
    expect(targets.find(t => t.id === 'portainer')?.steps.some(s => /Stacks|Add stack/.test(s.title))).toBe(true);
    expect(targets.find(t => t.id === 'coolify')?.steps.some(s => /Docker Compose/.test(s.title))).toBe(true);
  });
});

describe('buildReadme', () => {
  it('documents the files, quick start, and appends a guide when provided', () => {
    const readme = buildReadme(buildStack(), '## My Guide\n\nDo the thing.');
    expect(readme).toContain('# db stack');
    expect(readme).toContain('docker-compose.yml');
    expect(readme).toContain('.env');
    expect(readme).toContain('docker compose up -d');
    expect(readme).toContain('## My Guide');
  });
});
