apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: preview-app-staging
spec:
  project: default
  source:
    repoURL: https://github.com/org/repo
    path: staging
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true