import { prisma } from '../src/lib/db-utils'
import { packageYamlArtifact } from '../src/lib/deploy/packaging'
import crypto from 'node:crypto'

async function main() {
  // Build a simple sample stack for the generator
  const stackInput = {
    name: 'Sample Web Stack',
    namespace: 'stapelwerk',
    services: [
      {
        name: 'nginx',
        image: 'nginx:1.25-alpine',
        ports: [{ containerPort: 80, servicePort: 80 }],
        env: { NGINX_HOST: 'stapelwerk.local' },
        resources: { requests: { cpu: '100m', memory: '128Mi' } },
      },
    ],
  }

  const { path, checksum } = await packageYamlArtifact(stackInput as any, {})

  // Resolve stackId (create if missing)
  const stackSlug = 'sample-web-stack'
  let stack = await prisma.stack.findUnique({ where: { slug: stackSlug } })
  if (!stack) {
    stack = await prisma.stack.create({
      data: {
        id: crypto.randomUUID(),
        name: 'Sample Web Stack',
        slug: stackSlug,
        isPublic: false,
        isTemplate: false,
        status: 'draft',
      },
    })
  }

  // Resolve optional targetId
  const target = await prisma.deploymentTarget.findFirst({ where: { name: 'Local K3s' } })

  // Create artifact row
  const artifact = await prisma.deploymentArtifact.create({
    data: {
      type: 'yaml',
      checksum,
      location: path,
      metadata: JSON.stringify({ note: 'sample artifact generated by script' }),
      stackId: stack.id,
      targetId: target?.id ?? null,
    },
  })

  console.log('✅ Artifact created:')
  console.log({ id: artifact.id, downloadUrl: `/api/artifacts/${artifact.id}` })
}

main().catch((e) => {
  console.error(e)
  process.exit(1)
})